version: '2'
services:
  bluetooth-audio:
    network_mode: host
    restart: always
    build: ./bluetooth-audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - bluetoothcache:/var/cache/bluetooth
  airplay:
    build: ./airplay
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1
  network:
    build: ./network
    restart: always
    privileged: true
    network_mode: host
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
  spotify:
    build: ./spotify
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - spotifycache:/var/cache/raspotify
  snapclient:
    build: ./snapclient
    restart: always
    network_mode: host
    privileged: true
    labels: 
      io.balena.features.dbus: '1'
volumes:
  spotifycache:
  bluetoothcache:
